# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

clone:
  depth: full
pipelines:
  branches:
    dev-master:
      - step:
          name:
            Deploy to Development
          deployment:
            dev-master   
          script:
            - git add -A
            - git config --global user.email "kaustavofficial1808@gmail.com"
            - git config --global user.name "KAUSTAV BHATTACHARYA"
            - git remote set-url origin https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
            - git push -f https://heroku:$HEROKU_APP_KEY@git.heroku.com/$HEROKU_APP_NAME.git dev-master:master
            - npm install
            - npm test